[package]
name = "fyrox3dgame"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = ["executor", "executor-wasm", "executor-android", "game"]
resolver = "2"

[dependencies]
fyrox = "1"
fyroxed_base = "1"
rpg = { path = "./game" }

# Optimize the engine in debug builds, but leave project's code non-optimized.
# By using this technique, you can still debug you code, but engine will be fully
# optimized and debug builds won't be terribly slow. With this option, you can
# compile your game in debug mode, which is much faster (at least x3), than release.
[profile.dev.package."*"]
opt-level = 3


[workspace.dependencies]
fyrox = "1"
fyroxed_base = "1"
rpg = { path = "./game" }

